### PR TITLE
Add dependencies upgrading CHANGELOG

### PR DESCRIPTION
**Pull request by PerchunPak**
Do not forget update release date in [docs/CHANGELOG.md](https://github.com/hadialqattan/pycln/pull/134/files#diff-2bfab3db5cc1baf4c6d3ff6b19901926e3bdf4411ec685dac973e5fcff1c723bR13).

### CODE REVIEW

**Comment by hadialqattan** [comment]
@PerchunPak is there a purpose for releasing a quick release?

**Comment by hadialqattan** [comment]
I meant do you really need this update to happen quickly?

**Comment by hadialqattan** [comment]
I'll continue this PR and merge, but I don't think that I'll release a new version for the dependencies upgrade.

**Comment by hadialqattan** [comment]
@PerchunPak, for now, I'm gonna merge this PR, if you still want a quick release, please let me know.

**Comment by hadialqattan** [comment]
@PerchunPak not to forget, please send me your name and email so I can add you to the contributors' list!

**Comment by PerchunPak** [comment]
> @PerchunPak not to forget, please send me your name and email so I can add you to the contributors' list!

You can see it in local git client.
Email: perchunpak@gmail.com
Name: PerchunPak
IMG_20220423_092140


> @PerchunPak, for now, I'm gonna merge this PR, if you still want a quick release, please let me know.

Just this some strange see outdated versions in my `poetry.lock`, also I don't want pin dependence to gut commit. Anyway, thank you for your answer and merging my PRs!

**Comment by hadialqattan** [comment]
> > @PerchunPak not to forget, please send me your name and email so I can add you to the contributors' list!
> 
> You can see it in local git client. Email: [perchunpak@gmail.com](mailto:perchunpak@gmail.com) Name: PerchunPak IMG_20220423_092140
> 
> > @PerchunPak, for now, I'm gonna merge this PR, if you still want a quick release, please let me know.
> 
> Just this some strange see outdated versions in my `poetry.lock`, also I don't want pin dependence to gut commit. Anyway, thank you for your answer and merging my PRs!

Yeah I know it's available in git commits but sometimes people want to add a different email to the contributors' list.

Thanks again!

**Comment by hadialqattan** [comment]
> > @PerchunPak not to forget, please send me your name and email so I can add you to the contributors' list!
> 
> You can see it in local git client. Email: [perchunpak@gmail.com](mailto:perchunpak@gmail.com) Name: PerchunPak IMG_20220423_092140
> 
> > @PerchunPak, for now, I'm gonna merge this PR, if you still want a quick release, please let me know.
> 
> Just this some strange see outdated versions in my `poetry.lock`, also I don't want pin dependence to gut commit. Anyway, thank you for your answer and merging my PRs!

I have just released version `1.3.2`.

**Pull request merged**
