### PR TITLE
Ignore `from ... import *` imports in stub files

### LINKED ISSUE #152: [BUG] `from foo import *` imports should be ignored in stub files
Hi!

I see `pycln` recently added support for `.pyi` files. That's awesome!

I'm interested in possibly using `pycln` in typeshed's CI. However, it seems like there's one part of [PEP 484](https://peps.python.org/pep-0484/#stub-files) that `pycln` isn't quite compliant with when it comes to stub files, namely this:

> [...] all objects imported into a stub using `from ... import *` are considered exported. (This makes it easier to re-export all objects from a given module that may vary by Python version.)

If I run `pycln` on typeshed at the moment, it erroneously deletes a large number of "unused" `from foo import *` imports. These imports are all deliberate -- if a type checker sees a `from foo import *` import in a stub file `bar.pyi`, it understands all symbols from module `foo` to be re-exported in module `bar`.

Playing around with `pycln`, it looks like this one-line patch solves the problem:

```diff
diff --git a/pycln/utils/refactor.py b/pycln/utils/refactor.py
index 4739e72..a241fc8 100644
--- a/pycln/utils/refactor.py
+++ b/pycln/utils/refactor.py
@@ -279,7 +279,7 @@ class Refactor:

                 # Expand any import '*' before checking.
                 node, is_star = self._expand_import_star(node)
-                if is_star is None:
+                if is_star is None or (is_star and self._path.is_stub):
                     continue

                 # Get set of used names.
```

I'd file a PR, but I'm struggling a little bit with the test suite 😅 (I'm not too familiar with the advanced features of pytest, I'm afraid.)

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #152. No tests yet, I have no idea what I'm doing there 😅

### CODE REVIEW

**Comment by hadialqattan** [comment]
@AlexWaygood no worries bro, actually, the `Refactor._refactor` unit tests are very complicated and need refactoring 😅.

**Comment by hadialqattan** [comment]
@AlexWaygood BTW, I've moved the filetype check to another function avoiding unnecessary `scan.expand_import_star` calls.

(`scan.expand_import_star` is considered costy because it includes both pathfinding and static file analysis using `scan.ImportablesAnalyzer`)

**Comment by hadialqattan** [comment]
@AlexWaygood  I feel that I didn't provide enough context for why I've changed the point where we check for stub files. Please feel free to ask for further clarification.

**Comment by AlexWaygood** [comment]
> @AlexWaygood BTW, I've moved the filetype check to another function avoiding unnecessary `scan.expand_import_star` calls.
> 
> (`scan.expand_import_star` is considered costy because it includes both pathfinding and static file analysis using `scan.ImportablesAnalyzer`)

Nice! I tried it out on typeshed again, and can confirm the bug is still fixed :)

**Comment by hadialqattan** [comment]
> > @AlexWaygood BTW, I've moved the filetype check to another function avoiding unnecessary `scan.expand_import_star` calls.
> > (`scan.expand_import_star` is considered costy because it includes both pathfinding and static file analysis using `scan.ImportablesAnalyzer`)
> 
> Nice! I tried it out on typeshed again, and can confirm the bug is still fixed :)

Awesome! I'll merge the PR now!

**Comment by AlexWaygood** [comment]
FYI, typeshed is now using `pycln` as a pre-commit hook in CI :)

I think it's going to be a big quality-of-life improvement for us!

**Comment by hadialqattan** [comment]
> FYI, typeshed is now using `pycln` as a pre-commit hook in CI :)
> 
> I think it's going to be a big quality-of-life improvement for us!

Awesome! Thanks a lot for supporting Pycln.. btw, I'll add typeshed to the notable projects list that uses pycln!

https://github.com/hadialqattan/pycln#used-by

**Pull request merged**
