### PR TITLE
Expand pathspec range

### PR DESCRIPTION
**Pull request by Avasam**
`pathspec` 0.10.3 is properly marked as `py.typed`. I would like to use it, but it conflicts with pycln's version range.

`pip install pathspec>=0.10.3`
```
Collecting pathspec>=0.10.3
  Using cached pathspec-0.10.3-py3-none-any.whl (29 kB)
Installing collected packages: pathspec
  Attempting uninstall: pathspec
    Found existing installation: pathspec 0.10.2
    Uninstalling pathspec-0.10.2:
      Successfully uninstalled pathspec-0.10.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pycln 2.1.1 requires pathspec<0.10.0,>=0.9.0, but you have pathspec 0.10.3 which is incompatible.
```
image

So I changed the version range to allow `pathspec ^0.10` and ran `poetry lock` to update the lock file.

### CODE REVIEW

**Comment by hadialqattan** [comment]
@Avasam this pr lgtm so far, but are you sure that we really need to do a `poetry lock`? 

for now, I'll remove the lock file from this pr. waiting for your response before merging.

\+ thanks for contributing to Pycln.

**Comment by Avasam** [comment]
> @Avasam this pr lgtm so far, but are you sure that we really need to do a `poetry lock`?
> 
> for now, I'll remove the lock file from this pr. waiting for your response before merging.
> 
> + thanks for contributing to Pycln.

Tbh I'm less familiar with poetry. If poetry.lock works anything like a package-lock.json: usually it'll be the exact versions of all dependencies to be used by the CI (so any change in poetry should come with a lockfile update). So I did what I think is the proper procedure, but clearly the CI didn't like that.

As long as I can install both `pycln` and `pathspec>=0.10.3` together without a pip install warning/error I really don't mind.

**Comment by Avasam** [comment]
Thanks for the merge. Mind if I ask when there could be a new patch release?

**Comment by hadialqattan** [comment]
> Thanks for the merge. Mind if I ask when there could be a new patch release?

TBH, the next release will be released after at least solving the opened issues #187 and #185. expect that to get done within two weeks. Thank you.

**Comment by hadialqattan** [comment]
> Thanks for the merge. Mind if I ask when there could be a new patch release?

@Avasam a new Pycln release has just been released (`v2.1.3`).

**Pull request merged**
