### PR TITLE
Fix: RecursionError occurs when expanding a star import.

### LINKED ISSUE #71: [BUG] Recursion Errors
Every time I run it it gets stuck in this loop until it gets a precision error: 

>   \pycln\utils\scan.py", line 718, in generic_visit
    self.visit(item)
  File "python39\lib\ast.py", line 407, in visit
    return visitor(node)
  \pycln\utils\scan.py", line 104, in wrapper
    func(self, *args, **kwargs)
  \pycln\utils\scan.py", line 639, in visit_ImportFrom
    node = cast(ast.ImportFrom, expand_import_star(node, self._path))
  \pycln\utils\scan.py", line 855, in expand_import_star
    analyzer.visit(tree)
  File "python39\lib\ast.py", line 407, in visit
    return visitor(node)
  \pycln\utils\scan.py", line 718, in generic_visit
    self.visit(item)
  File "python39\lib\ast.py", line 407, in visit
    return visitor(node)
  \pycln\utils\scan.py", line 104, in wrapper
    func(self, *args, **kwargs)
  \pycln\utils\scan.py", line 639, in visit_ImportFrom
    node = cast(ast.ImportFrom, expand_import_star(node, self._path))
  \pycln\utils\scan.py", line 855, in expand_import_star
  RecursionError: maximum recursion depth exceeded while calling a Python object

### PR DESCRIPTION
**Pull request by hadialqattan**
Fixes: #71

### CODE REVIEW

**Comment by GameDungeon** [comment]
Your fix seems to just raise an error. May I suggest you use sys.setrecursionlimit to properly fix this?

**Comment by hadialqattan** [comment]
> Your fix seems to just raise an error. May I suggest you use sys.setrecursionlimit to properly fix this?

Even if we increased the recursion limit, we may end up with the same problem since `expand star` has no recursion limits, on top of that, this process shouldn't take a long time and/or a lot of memory. 😅

**Comment by GameDungeon** [comment]
Could you add a custom recursion value for the command line?

**Comment by GameDungeon** [comment]
I take that back setrecursionlimit can behave weirdly. The only way to fix this is to not have recursion. (Something I do think will happen)

**Comment by hadialqattan** [comment]
Hi again, 

I believe expanding star imports require using recursion anyway. A solution is more than welcome if any.

**Comment by GameDungeon** [comment]
I think I found why the recursion error happened. On any reasonable Libary, it would not hit the limit of 1000. I think what happened is an import cycle caused by an import in an if type checking clause we had in the library.

**Pull request merged**
